// Shared mock data used by both the public site (app.js) and the admin dashboard (dashboard.js).
// In a real product this would come from a database via an API — here it's just in-memory.

const LISTINGS = [
  {
    id: 1,
    title: "Clifftop Villa with Ocean Views",
    location: "Camps Bay, Cape Town",
    country: "South Africa",
    category: "Amazing views",
    price: 3200,
    rating: 4.97,
    reviews: 128,
    guests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 3,
    image: "https://picsum.photos/seed/camps-bay/800/600",
    gallery: ["https://picsum.photos/seed/camps-bay/800/600", "https://picsum.photos/seed/camps-bay-2/800/600"],
    amenities: ["Wifi", "Pool", "Kitchen", "Free parking", "Ocean view"],
    status: "Active",
    host: "Naledi M.",
  },
  {
    id: 2,
    title: "Minimalist A-Frame Cabin",
    location: "Franschhoek Valley",
    country: "South Africa",
    category: "Cabins",
    price: 1450,
    rating: 4.88,
    reviews: 64,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    image: "https://picsum.photos/seed/franschhoek/800/600",
    gallery: ["https://picsum.photos/seed/franschhoek/800/600", "https://picsum.photos/seed/franschhoek-2/800/600"],
    amenities: ["Wifi", "Fireplace", "Mountain view", "Kitchen"],
    status: "Active",
    host: "Naledi M.",
  },
  {
    id: 3,
    title: "Beachfront Bungalow",
    location: "Seminyak, Bali",
    country: "Indonesia",
    category: "Beachfront",
    price: 980,
    rating: 4.92,
    reviews: 210,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    image: "https://picsum.photos/seed/bali-bungalow/800/600",
    gallery: ["https://picsum.photos/seed/bali-bungalow/800/600", "https://picsum.photos/seed/bali-bungalow-2/800/600"],
    amenities: ["Wifi", "Pool", "Beach access", "Breakfast included"],
    status: "Active",
    host: "Wayan S.",
  },
  {
    id: 4,
    title: "Historic Loft near the Louvre",
    location: "1st Arrondissement, Paris",
    country: "France",
    category: "Trending",
    price: 2650,
    rating: 4.85,
    reviews: 96,
    guests: 3,
    bedrooms: 1,
    beds: 2,
    baths: 1,
    image: "https://picsum.photos/seed/paris-loft/800/600",
    gallery: ["https://picsum.photos/seed/paris-loft/800/600", "https://picsum.photos/seed/paris-loft-2/800/600"],
    amenities: ["Wifi", "Elevator", "Kitchen", "City view"],
    status: "Active",
    host: "Camille R.",
  },
  {
    id: 5,
    title: "Traditional Machiya Townhouse",
    location: "Higashiyama, Kyoto",
    country: "Japan",
    category: "Trending",
    price: 1890,
    rating: 4.99,
    reviews: 152,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    image: "https://picsum.photos/seed/kyoto-machiya/800/600",
    gallery: ["https://picsum.photos/seed/kyoto-machiya/800/600", "https://picsum.photos/seed/kyoto-machiya-2/800/600"],
    amenities: ["Wifi", "Garden", "Tatami rooms", "Kitchen"],
    status: "Paused",
    host: "Haruto K.",
  },
  {
    id: 6,
    title: "Santorini Cave Suite",
    location: "Oia, Santorini",
    country: "Greece",
    category: "Amazing views",
    price: 4100,
    rating: 4.96,
    reviews: 187,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    image: "https://picsum.photos/seed/santorini/800/600",
    gallery: ["https://picsum.photos/seed/santorini/800/600", "https://picsum.photos/seed/santorini-2/800/600"],
    amenities: ["Wifi", "Private pool", "Sea view", "Breakfast included"],
    status: "Active",
    host: "Elena P.",
  },
  {
    id: 7,
    title: "Brooklyn Brownstone Apartment",
    location: "Williamsburg, New York",
    country: "United States",
    category: "Trending",
    price: 2350,
    rating: 4.78,
    reviews: 143,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    image: "https://picsum.photos/seed/brooklyn/800/600",
    gallery: ["https://picsum.photos/seed/brooklyn/800/600", "https://picsum.photos/seed/brooklyn-2/800/600"],
    amenities: ["Wifi", "Washer", "Kitchen", "Rooftop access"],
    status: "Active",
    host: "Marcus T.",
  },
  {
    id: 8,
    title: "Alpine Chalet with Sauna",
    location: "Zermatt",
    country: "Switzerland",
    category: "Cabins",
    price: 5200,
    rating: 4.94,
    reviews: 88,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    image: "https://picsum.photos/seed/zermatt/800/600",
    gallery: ["https://picsum.photos/seed/zermatt/800/600", "https://picsum.photos/seed/zermatt-2/800/600"],
    amenities: ["Wifi", "Sauna", "Fireplace", "Mountain view", "Free parking"],
    status: "Active",
    host: "Lukas F.",
  },
  {
    id: 9,
    title: "Riad Courtyard House",
    location: "Medina, Marrakech",
    country: "Morocco",
    category: "Amazing views",
    price: 1120,
    rating: 4.9,
    reviews: 176,
    guests: 5,
    bedrooms: 3,
    beds: 3,
    baths: 2,
    image: "https://picsum.photos/seed/marrakech/800/600",
    gallery: ["https://picsum.photos/seed/marrakech/800/600", "https://picsum.photos/seed/marrakech-2/800/600"],
    amenities: ["Wifi", "Rooftop terrace", "Breakfast included", "Kitchen"],
    status: "Paused",
    host: "Yasmine B.",
  },
];

const BOOKINGS = [
  { id: 101, listingId: 1, guest: "Sarah Johnson", checkIn: "2026-07-10", checkOut: "2026-07-14", nights: 4, total: 12800, status: "Confirmed" },
  { id: 102, listingId: 3, guest: "David Chen", checkIn: "2026-07-12", checkOut: "2026-07-19", nights: 7, total: 6860, status: "Confirmed" },
  { id: 103, listingId: 6, guest: "Maria Garcia", checkIn: "2026-07-15", checkOut: "2026-07-18", nights: 3, total: 12300, status: "Pending" },
  { id: 104, listingId: 2, guest: "Tom Wilson", checkIn: "2026-07-20", checkOut: "2026-07-23", nights: 3, total: 4350, status: "Confirmed" },
  { id: 105, listingId: 8, guest: "Anna Kowalski", checkIn: "2026-08-01", checkOut: "2026-08-08", nights: 7, total: 36400, status: "Confirmed" },
  { id: 106, listingId: 4, guest: "James Okafor", checkIn: "2026-07-25", checkOut: "2026-07-27", nights: 2, total: 5300, status: "Cancelled" },
  { id: 107, listingId: 9, guest: "Fatima Al-Sayed", checkIn: "2026-08-05", checkOut: "2026-08-10", nights: 5, total: 5600, status: "Pending" },
  { id: 108, listingId: 7, guest: "Liam O'Brien", checkIn: "2026-07-18", checkOut: "2026-07-21", nights: 3, total: 7050, status: "Confirmed" },
];

const REVIEWS = [
  { id: 1, listingId: 1, guest: "Sarah Johnson", rating: 5, text: "Stunning views and an immaculate villa. Naledi was a fantastic host!", date: "2026-06-02" },
  { id: 2, listingId: 3, guest: "David Chen", rating: 5, text: "Woke up to the ocean every morning. Exactly as pictured.", date: "2026-05-28" },
  { id: 3, listingId: 6, guest: "Maria Garcia", rating: 4, text: "Beautiful suite, though the stairs down to it are steep with luggage.", date: "2026-05-14" },
  { id: 4, listingId: 8, guest: "Anna Kowalski", rating: 5, text: "The sauna after a day of skiing was unbeatable. Will be back.", date: "2026-04-30" },
  { id: 5, listingId: 4, guest: "James Okafor", guestNote: "", rating: 4, text: "Great location, a little noisy at night from the street below.", date: "2026-04-21" },
];

// Monthly revenue for the host's whole portfolio, used by the dashboard chart (mock, last 6 months).
const REVENUE_TREND = [
  { month: "Feb", revenue: 42500 },
  { month: "Mar", revenue: 51200 },
  { month: "Apr", revenue: 47800 },
  { month: "May", revenue: 63400 },
  { month: "Jun", revenue: 58900 },
  { month: "Jul", revenue: 71200 },
];

const CATEGORIES = ["All", "Amazing views", "Beachfront", "Cabins", "Trending"];
